aimsearch/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'aimsearch.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^search/', include('search.urls', namespace="search")),
    url(r'^admin/', include(admin.site.urls)),
)

search/urls.py
from django.conf.urls import patterns, url
from search import views

urlpatterns = patterns('',
	# ex: /polls/
	url(r'^$', views.index, name='index'),
	url(r'^grade/(?P<grade>\w+)/$', views.grade, name='grade'),
	url(r'^standard/(?P<pk>\d+)/$', views.StandardDetail.as_view(), name='standard'),
	url(r'^issues/(?P<issue>\d+)/$', views.issue, name='issue'),
)

search/models.py
from django.db import models

# Create your models here.
class Standard(models.Model):
	code = models.CharField(max_length=15)
	text = models.TextField()
	
	def __unicode__(self):
		return self.code
	
class Issue(models.Model):
	AIMS = 'AIMS Magazine'
	CLASSROOM_MAILBOX = 'Classroom Mailbox'
	OTHER = 'Other'
	name_choices = (
					(AIMS, 'AIMS Magazine'),
					(CLASSROOM_MAILBOX, 'Classroom Mailbox'),
					(OTHER, 'Other'),
					)
	source_name = models.CharField(	max_length = 30,
								choices = name_choices,
								default = AIMS)
	
	vol = models.CharField(max_length=5)
	no = models.PositiveIntegerField()
	year = models.CharField(max_length=15)
	
	def __unicode__(self):
		return self.year
	
class Activity(models.Model):
	issue = models.ForeignKey(Issue)
	standards = models.ManyToManyField(Standard)
	title = models.CharField(max_length=100)
	description = models.TextField()
	goals = models.TextField()
	
	def __unicode__(self):
		return self.title

search/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import auth
from django.core.context_processors import csrf
import datetime

from search.models import Standard, Issue, Activity

# Create your views here.
def index(request):
	issues = Issue.objects.all()
	return render_to_response('search/index.html', 
								{'issues': issues,
								})
	
def grade(request, grade):
	model = Standard
	if grade != 0:
		standards = Standard.objects.filter(code__startswith=grade)
	elif grade == 0:
		standards = Standard.objects.filter(code__startswith=K)
	return render(request, 'search/grade.html', {
					'standards': standards,
					})
					
class StandardDetail(generic.DetailView):
	model = Standard
	template_name = "search/standard.html"
	
def issue(request, issue):
	current_issue = Issue.objects.get(pk=issue)
	issue_activities = Activity.objects.filter(issue__id=issue)
	return render(request, "search/issue.html", {'activities': issue_activities,
													'issue': current_issue})

search/templates/search/3.html
<ul>
{% for standard in standards %}
	<li><a href="{% url 'search:standard' standard.id %}">{{ standard.code }}</a></li>
		<ul>
		<li>{{ standard.text }}</li>
		</ul>
{% endfor %}
</ul>

search/templates/search/grade.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'search/style.css' %}" />

<ul>
{% for standard in standards %}
	<li><a href="{% url 'search:standard' standard.id %}">{{ standard.code }}</a></li>
		<ul>
		<li>{{ standard.text }}</li>
		</ul>
{% endfor %}
</ul>

search/templates/search/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'search/style.css' %}" />

<h1>Welcome to AimSearch!</h1>

<center>
<p>Select a grade level:</p>
<a href="{% url 'search:grade' 'K' %}"><div class="button">Kindergarten</div></a>
<a href="{% url 'search:grade' 1 %}"><div class="button">Grade 1</div></a>
<a href="{% url 'search:grade' 2 %}"><div class="button">Grade 2</div></a>
<a href="{% url 'search:grade' 3 %}"><div class="button">Grade 3</div></a>
<a href="{% url 'search:grade' 4 %}"><div class="button">Grade 4</div></a>
<a href="{% url 'search:grade' 5 %}"><div class="button">Grade 5</div></a>
<a href="{% url 'search:grade' 6 %}"><div class="button">Grade 6</div></a>
</center>
<p>Or, search by issue:</p>
<ul>
{% for issue in issues %}
	<li><a href="{% url 'search:issue' issue.id %}">{{ issue }}</li>
{% endfor %}
</ul>

search/templates/search/issue.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'search/style.css' %}" />

<h1>{{ issue.source_name }} {{ issue }}</h1>

<ul>
{% for activity in activities %}
	<li><h4>{{ activity.title }}</h4></li>
		<ul>
		{% for standard in activity.standards.all %}
			<li><a href="{% url 'search:standard' standard.id %}">{{ standard }}</a></li>
		{% endfor %}
			<li>{{ activity.goals }}</li>
			<li>{{ activity.description }}</li>
		</ul>
{% endfor %}
</ul>

search/templates/search/standard.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'search/style.css' %}" />

<h1>{{ standard.code }}</h1>
<h4>{{ standard.text }}</h4>
<br><br>
<ul>
{% for activity in standard.activity_set.all %}
	<li>AIMS Magazine, {{ activity.issue }} - {{ activity }}</li>
	<ul>
		<li>{{ activity.goals }}</li>
		<li>{{ activity.description }}</li>
		<ul>
{% endfor %}
</ul>